# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://reactiveretro.com
title: Reactive Retro
email: hi@reactiveretro.com
author: Kyle Kemp
description: > # "Reactive Retro is a GPS-based RPG focused on cooperative gameplay!
copyright: 'Copyright &copy; 2016 Kyle Kemp. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    name: Facebook
    url: https://facebook.com/ReactiveRetro
  - title: google-plus
    name: Google+
    url: https://plus.google.com/communities/111450430548057393491
  - title: github
    name: Github
    url: https://github.com/reactive-retro/retro-app
